//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbmarka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbmarka()
        {
            this.dburunlers = new HashSet<dburunler>();
        }
    
        public int Id { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public string markaAdi { get; set; }
        public string aciklama { get; set; }
        public string img1 { get; set; }
    
        public virtual dbkategori dbkategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dburunler> dburunlers { get; set; }
    }
}
