//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbmusteri
    {
        public int Id { get; set; }
        public string musteriAdi { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string resim { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public Nullable<decimal> puan { get; set; }
        public string aciklama { get; set; }
        public string adres { get; set; }
        public Nullable<int> sehirId { get; set; }
        public Nullable<int> ilceId { get; set; }
    
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
    }
}
