//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbSatislar
    {
        public int Id { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> sepetId { get; set; }
        public Nullable<decimal> toplamFiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
        public Nullable<int> musteriId { get; set; }
    
        public virtual dbsepet dbsepet { get; set; }
        public virtual dburunler dburunler { get; set; }
    }
}
