//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsepet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbsepet()
        {
            this.dbSatislars = new HashSet<dbSatislar>();
        }
    
        public int Id { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
        public Nullable<int> musteriId { get; set; }
        public Nullable<decimal> birimfiyat { get; set; }
        public Nullable<decimal> toplamfiyat { get; set; }
        public Nullable<decimal> miktar { get; set; }
    
        public virtual dbkategori dbkategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbSatislar> dbSatislars { get; set; }
        public virtual dburunler dburunler { get; set; }
    }
}
