//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dburunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dburunler()
        {
            this.dbSatislars = new HashSet<dbSatislar>();
            this.dbsepets = new HashSet<dbsepet>();
        }
    
        public int Id { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<int> markaId { get; set; }
        public Nullable<int> birimId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> barkodNo { get; set; }
        public Nullable<decimal> alisFiyati { get; set; }
        public Nullable<decimal> satsFiyati { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> uretimTarih { get; set; }
        public Nullable<System.DateTime> TTE { get; set; }
        public string img2 { get; set; }
        public string urunAdi { get; set; }
    
        public virtual dbbirim dbbirim { get; set; }
        public virtual dbkategori dbkategori { get; set; }
        public virtual dbmarka dbmarka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbSatislar> dbSatislars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbsepet> dbsepets { get; set; }
    }
}
