//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbuser
    {
        public int Id { get; set; }
        public string userName { get; set; }
        public string userSurname { get; set; }
        public Nullable<int> sehirId { get; set; }
        public Nullable<int> ilceId { get; set; }
        public Nullable<int> departmandId { get; set; }
        public Nullable<decimal> maas { get; set; }
        public Nullable<int> izin { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    }
}
